# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-26 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Article'),
        ),
    ]
