name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo add-apt-repository universe
      - run: sudo apt update
      - run: sudo apt install python2 python2-dev
      - run: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
      - run: sudo python2 get-pip.py
      - run: make setup
      - run: |
          source venv/bin/activate
          make update
          make lint
          make test
