name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: |
          source venv/bin/activate
          make update
          make lint
          make test
